# Generated by Django 3.2 on 2023-07-04 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissionbackend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentadmission',
            name='address',
        ),
        migrations.RemoveField(
            model_name='studentadmission',
            name='city',
        ),
        migrations.RemoveField(
            model_name='studentadmission',
            name='country',
        ),
        migrations.RemoveField(
            model_name='studentadmission',
            name='dateOfBirth',
        ),
        migrations.RemoveField(
            model_name='studentadmission',
            name='email',
        ),
        migrations.RemoveField(
            model_name='studentadmission',
            name='fatherName',
        ),
        migrations.RemoveField(
            model_name='studentadmission',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='studentadmission',
            name='motherName',
        ),
        migrations.RemoveField(
            model_name='studentadmission',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='studentadmission',
            name='pinCode',
        ),
        migrations.RemoveField(
            model_name='studentadmission',
            name='state',
        ),
    ]
